import { Metadata } from 'next'
import { ServicePageTemplate } from '@/components/service-page-template'

const title = 'Wedding Restroom Trailer Rentals in Lansing & Mid-Michigan | Signature Luxe Events'
const description = 'Luxury wedding restroom trailer rentals for outdoor weddings, barn venues, estates, and backyard receptions across Lansing and Mid-Michigan with guest-first planning.'
const canonical = 'https://www.signatureluxeevents.com/wedding-restroom-trailer-rentals'
export const metadata: Metadata = { title, description, alternates: { canonical }, openGraph: { title, description, url: canonical } }

export default function Page() {
  return <ServicePageTemplate pageTitle='Wedding Restroom Trailer Rentals for Outdoor Michigan Celebrations' serviceName='Wedding restroom trailer rental' urlPath='/wedding-restroom-trailer-rentals' intro='From barn venues outside Lansing to private estates and backyard wedding weekends across Mid-Michigan, we help couples plan restroom access that feels polished, photo-ready, and comfortable for guests in formal attire.' ctaTitle='Check Wedding Weekend Availability' sections={[
    { heading: 'Designed for Outdoor Weddings, Barns, and Private Estates', paragraphs: ['Wedding timelines are different than standard events. Guests arrive dressed up, move between ceremony and cocktail hour, then surge again during dinner and dancing. A luxury trailer helps that entire flow stay comfortable and on-brand.', 'For rural barns, private estates, and backyard ceremonies in Lansing, Okemos, Haslett, Grand Ledge, and nearby communities, we help position trailers where they are convenient without interrupting your venue layout or photo moments.'] },
    { heading: 'Plan Capacity Around Cocktail Hour and Dinner Rush', paragraphs: ['The most common line spikes happen immediately after the ceremony, during cocktail hour, and right before dinner service. We size trailer options around those peaks so the reception keeps moving.', 'If your guest list includes children, older family members, or a long event schedule, we account for that too when recommending the best station count.'] },
    { heading: 'Guest Comfort Matters More at Formal Events', paragraphs: ['Wedding guests in suits, gowns, and heels expect more than a standard portable unit. Luxury trailers with flushing toilets, private stalls, sinks, mirrors, and lighting create a cleaner and more comfortable experience.', 'That comfort often translates to less stress for the host team and fewer interruptions to the planner, venue coordinator, or catering schedule.'] },
    { heading: 'Photo-Friendly Exterior and Reception Layout Planning', paragraphs: ['Restroom placement affects more than convenience. We help select a setup spot that supports guest access while staying out of key photo angles, bar lines, and entertainment zones.', 'For tighter properties and backyard weddings, we review driveway access, turning space, and ground conditions before delivery day.'] },
    { heading: 'Reserve 2 to 4 Months Ahead for Peak Dates', paragraphs: ['Spring and fall Saturdays in Mid-Michigan often book first, especially for wedding weekends. Planning 2 to 4 months ahead gives the best chance of securing your preferred trailer size.', 'If your date is closer, we can still review availability and suggest alternatives that keep guest comfort high.'] },
    { heading: 'Serving Lansing and Nearby Wedding Markets', paragraphs: ['We support weddings across Lansing, East Lansing, DeWitt, Jackson, Howell, Flint, Ann Arbor, Grand Rapids, and surrounding communities. Delivery timing is coordinated around venue access windows and rehearsal schedules.', 'If you are also comparing options for engagement parties, rehearsal dinners, or after-parties, see our private event page and full luxury rental overview for planning continuity.'] },
  ]} faqs={[
    { q: 'How far in advance should we book wedding restroom trailers?', a: 'For popular spring and fall dates, 2 to 4 months is ideal. We can also check shorter timelines based on current inventory and route availability.' },
    { q: 'Can you deliver to barn venues and private properties?', a: 'Yes. We frequently plan deliveries for barns, estates, and backyard weddings, including access and placement checks before delivery.' },
    { q: 'How do you size trailers for reception flow?', a: 'We estimate based on guest count, event duration, and traffic peaks during cocktail hour, dinner, and dancing transitions.' },
    { q: 'Can we place the trailer away from ceremony photos?', a: 'Absolutely. We help identify practical placement that supports guest convenience while protecting key photo and décor sightlines.' },
    { q: 'Do you serve outside Lansing?', a: 'Yes. We serve Mid-Michigan and nearby regional markets including East Lansing, Okemos, Haslett, Jackson, Howell, Flint, Ann Arbor, and Grand Rapids.' },
  ]} resourceImageSrc='/images/Wedding Trailer.png' resourceImageAlt='Wedding restroom trailer setup near outdoor reception venue' resourceEyebrow='Wedding Planning' resourceTitle='Helpful Wedding Restroom Planning Resources' resourceDescription='Use these pages to map coverage, compare options, and build a smooth wedding weekend guest experience.' />
}
