import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { Header } from '@/components/layout/header'
import { Footer } from '@/components/layout/footer'
import { Button } from '@/components/ui/button'
import { breadcrumbJsonLd, localBusinessJsonLd } from '@/lib/seo-schema'
import { cityPages } from '@/lib/seo'

type CityExtra = { intro: string; nearby: string; venueNote: string; useCases: string[]; faqs: { q: string; a: string }[] }
const cityContent: Record<string, CityExtra> = {
  'lansing-mi': { intro: 'Lansing events range from downtown fundraisers to backyard celebrations, and each site needs practical restroom logistics.', nearby: 'East Lansing, Holt, Mason, and Grand Ledge', venueNote: 'We plan around mixed urban and residential access patterns across the capital region.', useCases: ['wedding weekends', 'corporate and nonprofit events', 'city festivals', 'temporary facility support'], faqs: [{ q: 'How early should I reserve in Lansing?', a: 'Peak weekends are best reserved in advance, especially spring and fall.' }, { q: 'Can you serve parks and private properties?', a: 'Yes, we coordinate access and setup planning for both.' }, { q: 'Do you offer multi-day rentals?', a: 'Yes, including service scheduling for longer events.' }, { q: 'Do you deliver beyond Lansing city limits?', a: 'Yes, throughout Mid-Michigan and nearby markets.' }] },
  'east-lansing-mi': { intro: 'East Lansing often combines campus-adjacent events with private gatherings that need polished guest amenities.', nearby: 'Lansing, Okemos, Haslett, and DeWitt', venueNote: 'We account for tighter load-in windows common around university-area venues.', useCases: ['alumni and graduation events', 'weddings', 'private parties', 'corporate functions'], faqs: [{ q: 'Do you serve East Lansing year-round?', a: 'Yes, based on date availability and routing.' }, { q: 'Can you help with utility planning?', a: 'Yes, we review power and water options before delivery.' }, { q: 'Are trailers suitable for formal events?', a: 'Yes, they are designed for elevated guest comfort.' }, { q: 'Can I request a quote online?', a: 'Yes, through our quote form.' }] },
  'okemos-mi': { intro: 'Okemos hosts private estate events, school celebrations, and community gatherings where comfort and clean presentation matter.', nearby: 'Haslett, East Lansing, Williamston, and Lansing', venueNote: 'We support suburban properties with driveway and yard placement planning.', useCases: ['backyard graduations', 'wedding receptions', 'corporate picnics', 'holiday parties'], faqs: [{ q: 'Can you place a trailer at a private home?', a: 'Yes, after confirming access and surface conditions.' }, { q: 'Do you support graduation season demand?', a: 'Yes, with early reservation recommended.' }, { q: 'Do you deliver to nearby townships?', a: 'Yes, throughout the Okemos area.' }, { q: 'Can you help pick trailer size?', a: 'Yes, based on guest count and duration.' }] },
  'haslett-mi': { intro: 'Haslett events often center on neighborhood celebrations and private outdoor gatherings that need added restroom capacity.', nearby: 'Okemos, East Lansing, Meridian Township, and Bath', venueNote: 'We plan access around residential streets and property layouts.', useCases: ['family reunions', 'birthday celebrations', 'graduation parties', 'small corporate events'], faqs: [{ q: 'Is Haslett in your regular service area?', a: 'Yes, it is part of our Mid-Michigan coverage.' }, { q: 'Can this reduce indoor traffic at parties?', a: 'Yes, that is a major benefit for private hosts.' }, { q: 'Do you handle setup and pickup?', a: 'Yes, full delivery and pickup are included.' }, { q: 'Can rentals span a full weekend?', a: 'Yes, weekend and multi-day options are available.' }] },
  'grand-ledge-mi': { intro: 'Grand Ledge events include river-area gatherings, weddings, and community celebrations that need dependable temporary facilities.', nearby: 'Lansing, Delta Township, Eagle, and Portland', venueNote: 'We coordinate placement for parks, private land, and mixed-surface sites.', useCases: ['weddings and receptions', 'community festivals', 'private parties', 'contractor support'], faqs: [{ q: 'Do you deliver to Grand Ledge venues?', a: 'Yes, across city and surrounding rural areas.' }, { q: 'Can you support multi-day events?', a: 'Yes, including service intervals when needed.' }, { q: 'What utilities are required?', a: 'We review power and water requirements during planning.' }, { q: 'Are long-term rentals available?', a: 'Yes, for projects and temporary facilities.' }] },
  'dewitt-mi': { intro: 'DeWitt combines residential celebrations and project-based site needs where clean temporary restroom access is important.', nearby: 'Lansing, Bath, St. Johns, and East Lansing', venueNote: 'We help plan efficient trailer placement at private properties and work locations.', useCases: ['graduation parties', 'weddings', 'company events', 'construction support'], faqs: [{ q: 'Do you serve DeWitt year-round?', a: 'Yes, with scheduling based on availability.' }, { q: 'Can you advise on station count?', a: 'Yes, we provide sizing recommendations.' }, { q: 'Do you support construction rentals?', a: 'Yes, including recurring service schedules.' }, { q: 'Can I book for a weekend event?', a: 'Yes, weekend bookings are common.' }] },
  'jackson-mi': { intro: 'Jackson hosts regional events, private gatherings, and temporary project needs that benefit from luxury restroom access.', nearby: 'Spring Arbor, Michigan Center, Napoleon, and Grass Lake', venueNote: 'We coordinate timing and placement for both city and rural properties.', useCases: ['wedding weekends', 'community events', 'corporate gatherings', 'facility outage support'], faqs: [{ q: 'Do you deliver to Jackson County?', a: 'Yes, we serve Jackson and nearby communities.' }, { q: 'Can you help for temporary outages?', a: 'Yes, we support short-term temporary needs.' }, { q: 'Are trailers suitable for donor events?', a: 'Yes, they are ideal for polished guest-facing events.' }, { q: 'How do I request pricing?', a: 'Submit your event date, location, and headcount through the quote form.' }] },
  'howell-mi': { intro: 'Howell events range from private celebrations to downtown-adjacent gatherings where guest comfort and site logistics both matter.', nearby: 'Brighton, Fowlerville, Hartland, and Pinckney', venueNote: 'We plan around varied property layouts and event access windows.', useCases: ['backyard parties', 'weddings', 'corporate events', 'long-term temporary facilities'], faqs: [{ q: 'Is Howell within your delivery area?', a: 'Yes, Howell is in our regional coverage.' }, { q: 'Can you handle backyard setups?', a: 'Yes, after site access confirmation.' }, { q: 'Do you offer multi-day service?', a: 'Yes, depending on event duration and needs.' }, { q: 'Can you support construction jobs?', a: 'Yes, with long-term rental options.' }] },
  'flint-mi': { intro: 'Flint-area events and projects often require dependable temporary infrastructure with clear scheduling and service planning.', nearby: 'Grand Blanc, Burton, Davison, and Fenton', venueNote: 'We coordinate placement for urban venues, community spaces, and private properties.', useCases: ['community festivals', 'weddings', 'corporate functions', 'public works support'], faqs: [{ q: 'Do you serve the Flint metro area?', a: 'Yes, including nearby communities.' }, { q: 'Can you support municipal-style events?', a: 'Yes, we coordinate for larger public gatherings.' }, { q: 'Is VIP presentation available?', a: 'Yes, luxury units are ideal for guest-facing occasions.' }, { q: 'Do you offer emergency rentals?', a: 'Yes, based on current availability.' }] },
  'grand-rapids-mi': { intro: 'Grand Rapids has a strong event market with weddings, corporate activations, and regional gatherings that need elevated restroom options.', nearby: 'Wyoming, Kentwood, Ada, and Walker', venueNote: 'We coordinate around busier venue calendars and structured load-in schedules.', useCases: ['wedding receptions', 'corporate galas', 'donor events', 'community festivals', 'temporary project support'], faqs: [{ q: 'Do you deliver to Grand Rapids event venues?', a: 'Yes, throughout the greater Grand Rapids area.' }, { q: 'Can you support upscale corporate events?', a: 'Yes, including VIP-focused restroom planning.' }, { q: 'How early should we reserve?', a: 'Early booking is best for prime weekend dates.' }, { q: 'Do you handle setup logistics?', a: 'Yes, including placement and utility coordination.' }] },
  'ann-arbor-mi': { intro: 'Ann Arbor events include formal weddings, university-adjacent gatherings, and private celebrations that prioritize guest experience.', nearby: 'Ypsilanti, Saline, Dexter, and Chelsea', venueNote: 'We help coordinate tight access windows and polished event presentation expectations.', useCases: ['weddings', 'private estate parties', 'corporate and donor events', 'community gatherings'], faqs: [{ q: 'Do you provide service in Ann Arbor?', a: 'Yes, across Ann Arbor and nearby communities.' }, { q: 'Can this support upscale events?', a: 'Yes, luxury trailers are designed for elevated guest comfort.' }, { q: 'Do you assist with capacity planning?', a: 'Yes, we recommend sizing by attendance and timeline.' }, { q: 'Can I book for a weekend plus setup day?', a: 'Yes, scheduling can be customized.' }] },
}

const getCityData = (slug: string) => { const base = cityPages.find((c) => c.slug === slug); return base ? { ...base, ...cityContent[slug] } : null }
export function generateStaticParams() { return cityPages.map((c) => ({ citySlug: c.slug })) }
export function generateMetadata({ params }: { params: { citySlug: string } }): Metadata { const data = getCityData(params.citySlug); if (!data) return {}; const title = `Luxury Restroom Trailer Rentals in ${data.city}, MI`; const description = `Luxury restroom trailer rentals in ${data.city}, MI for weddings, private parties, corporate events, festivals, and temporary project needs.`; const canonical = `https://www.signatureluxeevents.com/service-areas/${data.slug}`; return { title, description, alternates: { canonical }, openGraph: { title, description, url: canonical } } }

export default function CityPage({ params }: { params: { citySlug: string } }) { const data = getCityData(params.citySlug); if (!data) notFound(); const business = localBusinessJsonLd(data.city); const breadcrumbs = breadcrumbJsonLd([{ name: 'Home', item: '/' }, { name: 'Service Areas', item: '/service-areas' }, { name: `${data.city}, MI`, item: `/service-areas/${data.slug}` }]); const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: data.faqs.map((f) => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })) };
return <><script type='application/ld+json' dangerouslySetInnerHTML={{ __html: JSON.stringify(business) }} /><script type='application/ld+json' dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbs) }} /><script type='application/ld+json' dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><Header /><main className='container mx-auto px-4 lg:px-8 py-16 space-y-8'><h1 className='text-4xl font-serif font-semibold text-navy'>Luxury Restroom Trailer Rentals in {data.city}, MI</h1><p className='text-lg text-muted-foreground'>{data.intro} We also serve {data.nearby}.</p><div><Button asChild><Link href='/request-quote'>Check Availability in {data.city}</Link></Button></div><h2 className='text-2xl font-semibold text-navy'>Restroom Trailer Rentals for {data.city} Events</h2><p>{data.venueNote}</p><h2 className='text-2xl font-semibold text-navy'>Weddings, Private Parties, and Outdoor Venues</h2><p>From elegant wedding weekends to backyard celebrations, we help hosts match trailer size and placement to guest flow and site constraints.</p><h2 className='text-2xl font-semibold text-navy'>Corporate, Festival, and Community Event Support</h2><p>We support corporate functions, nonprofit events, and public gatherings where crowd flow, cleanliness, and polished presentation all matter.</p><h2 className='text-2xl font-semibold text-navy'>Construction, Long-Term, and Temporary Restroom Needs</h2><p>Our team also supports project-based and temporary infrastructure needs with dependable delivery, pickup, and recurring service planning.</p><h2 className='text-2xl font-semibold text-navy'>Planning Delivery, Power, Water, and Placement</h2><p>Before delivery, we confirm access paths, surface suitability, and utility planning so setup stays smooth and timeline-friendly.</p><h2 className='text-2xl font-semibold text-navy'>Nearby Communities We Serve</h2><p>{data.city} service coverage includes {data.nearby} and surrounding Mid-Michigan communities.</p><ul className='list-disc pl-6 space-y-1'>{data.useCases.map((u) => <li key={u}>{u}</li>)}</ul><h2 className='text-2xl font-semibold text-navy'>FAQs for {data.city}, MI</h2><div className='space-y-4'>{data.faqs.map((f) => <div key={f.q}><h3 className='font-semibold'>{f.q}</h3><p>{f.a}</p></div>)}</div></main><Footer /></>
}

