create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

create policy "Authenticated users can read their own admin record"
on public.admin_users
for select
to authenticated
using (lower(email) = lower((auth.jwt() ->> 'email')));

insert into public.admin_users (email)
values ('flintstoneseo@gmail.com')
on conflict (email) do nothing;
